name: Setup Node.js
description: Setup Node.js

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        run_install: false
        package_json_file: 'tests/package.json'

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: 'tests/.node-version'
        cache: 'pnpm'
        cache-dependency-path: "tests/package-lock.json"

    - name: Install dependencies
      shell: bash
      run: cd tests && pnpm i --frozen-lockfile
