version: '3.8'

services:
  ic_websocket_gateway:
    image: omniadevs/ic-websocket-gateway:latest
    platform: linux/amd64
    container_name: ic-websocket-gateway
    restart: unless-stopped
    volumes:
      - ./volumes/ic-ws-gateway/data:/ic-ws-gateway/data
    networks:
      - ic-ws-gateway-network

  otlp_collector:
    image: otel/opentelemetry-collector:0.92.0
    container_name: otlp_collector
    restart: unless-stopped
    ports:
      - "4317:4317" # otlp grpc receiver
    volumes:
      - ./telemetry/otel-config.yaml:/etc/otelcol/config.yaml
    networks:
      - ic-ws-gateway-network

  # https://grafana.com/docs/grafana-cloud/send-data/metrics/metrics-prometheus/
  prometheus:
#    image: prom/prometheus
    image: local/prometheus
    build:
      context: ./
      dockerfile: ./telemetry/prometheus/Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    env_file:
      - .env
    networks:
      - ic-ws-gateway-network

networks:
  ic-ws-gateway-network:
    name: ic-ws-gateway-network
