{
 "title": "IC Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of client connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (clients_connected_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active pollers",
   "type": "gauge",
   "description": "This graph represent the number of active pollers approximately in realtime (worst case 10s of scraping delay)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_pollers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clients connected by canister id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "clients_connected_count", "legendFormat": "{{canister_id}}" }
   ]
  },
  {
   "title": "Tls resolution time by client id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tls_resolution_time{quantile=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to open connection by client id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "connection_opening_time{quantile=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client connected by day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (sum_over_time(clients_connected_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client connected by hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (sum_over_time(clients_connected_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}