global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: gateway
    honor_labels: true
    static_configs:
      - targets: [ 'ic_websocket_gateway:9000' ]

remote_write:
  - url: ${GRAFANA_PROMETHEUS_ENDPOINT}
    basic_auth:
      username: ${GRAFANA_PROMETHEUS_USERNAME}
      password: ${GRAFANA_PROMETHEUS_TOKEN}
