name: Integration tests

# only run when a commit is pushed to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust
        with:
          cache-key: "build-native"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "tests/package-lock.json"

      - uses: dfinity/setup-dfx@main
        with:
          dfx-version: 0.18.0

      - name: Prepare environment for integration tests
        run: ./scripts/prepare_integration_tests.sh

      - name: Run integration tests
        run: ./scripts/ci_cd_test_integration.sh
