name: Load tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust
        with:
          cache-key: "build-native"

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-dfx

      - name: Prepare environment for load tests
        run: ./scripts/prepare_tests.sh

      - name: Execute load tests
        run: ./scripts/ci_cd_test_load.sh

      - name: Upload load test results
        if: always()  # This ensures the upload happens even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: load-test-results
          path: tests/reports/gateway_load_tests.json
