name: Rust tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust
        with:
          cache-key: "build-native"

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features --workspace -- -Dwarnings

      - name: Run unit tests
        run: ./scripts/unit_test.sh
